# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ccd6343807faafe16d56bcc1a2bff9e4c4e9bfcd8c47c5fb05da8ffbdd9c179bafd3f0b588d17e0b47db1a3f0e7e918124a14d9e344281497f35ff955c7fceb

test:
  secret_key_base: 54243a5b6732803b48c91d1ae695650ac86e464f4f9c6ded03b3c9cec94b5332b7e9f4ab203936a2e4b6ce7622b47c688d574abb5f243e69fd852c651bd682e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
